### ISSUE TITLE
Activation Fails on ILIAS 5.1.3

### ISSUE THREAD

**Issue by imonk** [hrz-unimr/Ilias.RESTPlugin#27]
Hi guys,

when downloading your latest commit and installing it on our CentOS machine (php 5.6.2) it issues:
     
        implode(): Invalid arguments passed

there's nothing in the log, unfortunately. Is there a way to increase the log-level? 
Your version 1.3 (commit ac1a355) is able to activate and opens the admin-panel but stays completely blank without the apollon client or the ability to save a new route (no log entries created).
This feels to me like some DB-query issues, would you have any idea / suggestions?
thx

**Comment by disc5** [comment]
Hi imonk,

it is indeed hard to locate the exact problem from this error description. We definitely see the necessity for better logging capabilities in the future.

Strictly speaking, the commit you mention does not belong to the version v.1.3.1 anymore, but belongs to a series of adaptions of the admin interface that reaches into the v.1.4.x version. These adaption were necessary due to a major refactoring after Nov 2015-Feb2016. Sorry for the confusion and the trouble.

Our suggestion: 
* Use v.1.3.1 as is (zip/tar File) from https://github.com/hrz-unimr/Ilias.RESTPlugin/releases/tag/v1.3.1. (This one should be stable.)
* Use v.1.4.3 but with no guarantees for the **extension** routes yet
* Wait for v.1.5.0 (and skip the hassle with 1.3.1+/1.4.x)

Cheers,
Dirk

**Comment by imonk** [comment]
Hi Dirk,
I found the problem: class.ilDBupdate->applyUpdateNr runs through your dbupdates.php and issues the horrile   `eval($code)`
In case of update <#6> you set the `sql `variable which also is used in `applyUpdateNr`. Then it's not length 0 anymore and `execQuery($this->db, implode("\n", $sql))` (line 490) gets a string as (invalid) 2nd argument instead of an array.
I changed the first two lines of update #6 in your dbupdate.php and now the plugin activates.

 ```
 $sql_1    = 'SELECT id FROM ui_uihk_rest_client WHERE api_key = \'apollon\'';
  $query  = $ilDB->query($sql_1);
```

However, still no changes are saved made in the admin panel, somewhere along the way a 

> Non-static method MDB2::isError() should not be called statically, assuming $this from incompatible context

Error is dropped following the ` \RESTPlugin\Bootstrap::init();`

**Comment by Hufschmidt** [comment]
_I'm FINALLY finished setting-up various ILIAS clusters and can get back to the real work..._

I've reinstalled a clean Version of ILIAS 5.0.11 and fetched the latest REST master branch. Installation went well and apart from a short auto-detection hickup the admin-panel works fine now too.
My guess is, this is proably not the version you are using?

### A bit of history:
Starting with e93611af77a4a9cb39d762b8ba4638c8941ec72d (25 Nov 2015) there was **A LOT** of refactoring and under-the-hood cleaning of old code, which lead to a lot of breaking changes, esspecially extensions and the admin-panel which relied on (core) routes.

The Admin-Panel should be working now and the extensions are also beeing worked on, but we aren't quite finished with those yet.
