### ISSUE TITLE
Downloading courses

### ISSUE THREAD

**Issue by alexChueshev** [hrz-unimr/Ilias.RESTPlugin#30]
Hi guys,
is there a way to download course or learning module using REST endpoints?
Thanks!

**Comment by Hufschmidt** [comment]
Hi Alex,

to my knowledge there is non (yet), but since we'll be needing this ourselfs, we'll implement one at _some point in the future_.

If you'd like to start the hard work by digging through ILIAS in order to find where/how this information is exposed would greatly speed up a working implementation, since this is always the hardest part about implementing a new route... :see_no_evil:

Best Regards
