### ISSUE TITLE
Call to undefined method Common::FlowAll 

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#36]
At least in versions 1.5.0 - 1.5.2 there is a mistake in the Misc.php line 91 (Customizing\global\plugins\Services\UIComponent\UserInterfaceHook\REST\RESTController\core\oauth2_v2\models). 
It is: `Common::FlowAll(...`
It should be: `self::FlowAll(...`

It is already fixed in v 1.6.0

**Comment by Hufschmidt** [comment]
Thank you for pointing this out. Due to available time constraints I'll not be doing back-ports. :scream:
I know you probably reverted to 1.5.0 because of my sloppy 1.6.0 release, for which I'm really sorry. :dizzy_face:

I'm happy to announce though, that I should have been able to fix most issues introduced in 1.6 with the release of **1.6.1**. :eyes:
