### ISSUE TITLE
Refresh-Token option is not activated

### ISSUE THREAD

**Issue by bastianleirpo** [hrz-unimr/Ilias.RESTPlugin#44]
When creating a new rest client i activate all options and add all routes. After i saved the client the option "Enable Refresh-Token support for Authorization Code" isn't enabled. I need to go a second time into the client details and activate it. Afterwards its set correctly.

**Comment by Hufschmidt** [comment]
Thanks for pointing this out. The admin-panel was using 1/0 values instead of true/false values, models for updating the client have logic to map this kind of information, but the client constructor has not.
I should fix this long-term, for now I corrected the value send by the admin-panel. 

Again thanks for pointing this out. :smile:
