### ISSUE TITLE
Access to all routes without permission

### ISSUE THREAD

**Issue by eqsoft** [hrz-unimr/Ilias.RESTPlugin#8]
I could access all routes with a valid api_key and root user token but without setting any permissions in the Rest administration

**Comment by Hufschmidt** [comment]
I think I noticed something similar when using a route I should not be authorised to use. For example when I access 
http://localhost/restplugin.php/dev/hello
without any token I get rejected as expected.
But when I access it using a token generated using the default (debug) api_key *apollon* (which does not have this route listed unter its permissions) I get a valid return value from
http://localhost/restplugin.php/dev/hello
This should not be the case.

**Comment by Hufschmidt** [comment]
After some research I have the following conclusions:
* Tokens that are generated by providing an admin account will have access to all routes by default, as long as the supplied token is valid.  This is probably by design.  
* There are three different authentication requirements:
  * "authenticate" - Requires valid token AND access to route
  * "authenticateTokenOnly" - Requires valid token (no other permissions are checked)
  * "authenticateILIASAdminRole" - Require valid token and token needs to be generated with admin-account
* Each route can define its own authentification requirement. (above)

**My Gist**  
I'd say this design is relatively robust, but I also feel there need to be some additions:
* Routes that do not require a token (all can use it) should not be listed in the configuration
* Routes that require an admin-account should either
   * not be listed in the configuration
   * implementation should be changed such that admins don't have access to all routes, eg ignoring permissions [I'd vote for this]
* For each route there really needs to be a complete API-Documentation [personally I'd prever javadoc + doxygen] detailing:
  * Route URL
  * Route Parameters
    * URL-Parameters (Where used)
    * BODY-Parameters (detailed list / JSON shema)
    * For each parameter a short description
  * Route VERB (GET, POST, PUT, DELETE, ...)
  * Authentication requirement (all, by permission, only token, only admin)
  * Return body (detailed list / JSON shema)
    * Every key/value pair should have a short description

**Further Issue**  
Currently some routes use authenticateTokenOnly but internally check wether user is admin (eg. */clients*). This seems to run counter to the authentification shema?!

**Comment by Hufschmidt** [comment]
Another (related) issue: Non-admins can log into plugin-configuration.
